spring:
  jpa:
    hibernate:
      ddl-auto: validate
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE

  profiles:
    include: local_db
#  sql:
#    init:
#      mode: always
