GET http://localhost:8080/api/employee?isActive=1&page=0&size=3&rankNo=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDUiLCJpYXQiOjE3MTI2MzE0NjksImV4cCI6MTcxMjY0MjI2OX0.7dphFos9W9vBxP2Ej7_QKxRlsoqs1ErE7SAfUB_Abi0

